### PR TITLE
Chat improvements

### PR DESCRIPTION
**Pull request by kush458**
Update summary:
- Refactored chat, user models and existing APIs (this also gives us the option to delete a chat if all users leave it)
- Made some UI improvements to improve the send message text area and replace groupId with chat-name

### CODE REVIEW

**Review by awctw — COMMENTED** [review]
There seems to be a lot of files from Gantt Chart being changed, is this intended?

**Comment by kush458** [comment]
> There seems to be a lot of files from Gantt Chart being changed, is this intended?

Um...I think that's cuz I merged with main in a prior commit after progress 4

**Comment by awctw** [comment]
> > There seems to be a lot of files from Gantt Chart being changed, is this intended?
> 
> Um...I think that's cuz I merged with main in a prior commit after progress 4

That is strange, if it is currently in main it should not be showing up in the diff

**Comment by kush458** [comment]
> > > There seems to be a lot of files from Gantt Chart being changed, is this intended?
> > 
> > 
> > Um...I think that's cuz I merged with main in a prior commit after progress 4
> 
> That is strange, if it is currently in main it should not be showing up in the diff

Ok I think I recall now, so after I merged, I had to fix some conflicts and it's probably due to that. I had to delete a duplicate ChartSettingModal.jsx file in accordance with what Kenneth did in main...

**Comment by awctw** [comment]
> > > > There seems to be a lot of files from Gantt Chart being changed, is this intended?
> > > 
> > > 
> > > Um...I think that's cuz I merged with main in a prior commit after progress 4
> > 
> > 
> > That is strange, if it is currently in main it should not be showing up in the diff
> 
> Ok I think I recall now, so after I merged, I had to fix some conflicts and it's probably due to that. I had to delete a duplicate ChartSettingModal.jsx file in accordance with what Kenneth did in main...

Ok for the chat part I think it is good to go but I would have to defer to kenneth regarding the gantt part since not sure what is going on.

**Comment by leungkenneth** [comment]
Just noticed this as I'm not subscribed to this thread: please @ me or add me to reviewers in the future if you need me for something. 

The chart stuff looks good to me: basically all of it is as it is on main save for an auto-merged change with Annabelle's deploy changes in client/src/store/chartSettings/service.js.

Before the chat branch is merged to main please let me know if there are any chart stuff diffs for some reason.

> > > > > There seems to be a lot of files from Gantt Chart being changed, is this intended?
> > > > 
> > > > 
> > > > Um...I think that's cuz I merged with main in a prior commit after progress 4
> > > 
> > > 
> > > That is strange, if it is currently in main it should not be showing up in the diff
> > 
> > 
> > Ok I think I recall now, so after I merged, I had to fix some conflicts and it's probably due to that. I had to delete a duplicate ChartSettingModal.jsx file in accordance with what Kenneth did in main...
> 
> Ok for the chat part I think it is good to go but I would have to defer to kenneth regarding the gantt part since not sure what is going on.

**Comment by kush458** [comment]
> Just noticed this as I'm not subscribed to this thread: please @ me or add me to reviewers in the future if you need me for something.
> 
> The chart stuff looks good to me: basically all of it is as it is on main save for an auto-merged change with Annabelle's deploy changes in client/src/store/chartSettings/service.js.
> 
> Before the chat branch is merged to main please let me know if there are any chart stuff diffs for some reason.
> 
> > > > > > There seems to be a lot of files from Gantt Chart being changed, is this intended?
> > > > > 
> > > > > 
> > > > > Um...I think that's cuz I merged with main in a prior commit after progress 4
> > > > 
> > > > 
> > > > That is strange, if it is currently in main it should not be showing up in the diff
> > > 
> > > 
> > > Ok I think I recall now, so after I merged, I had to fix some conflicts and it's probably due to that. I had to delete a duplicate ChartSettingModal.jsx file in accordance with what Kenneth did in main...
> > 
> > 
> > Ok for the chat part I think it is good to go but I would have to defer to kenneth regarding the gantt part since not sure what is going on.

Sounds good...will let you know about any future diffs

**Pull request merged**
