### PR TITLE
Refactoring

### PR DESCRIPTION
**Pull request by kush458**
Refactored file structure into client and server folders. Feel free to refactor further as needed!

### CODE REVIEW

**Review by awctw — COMMENTED** [review]
Could you include in the gitignore the node_modules

**Comment by kush458** [comment]
Done!

**Comment by awctw** [comment]
> Done!

Is it possible to create a new pr so that the node_modules wont be merged in? It looks like the pr still has the node_modules.

**Comment by kush458** [comment]
Hmm.. I see. How about I just delete node_modules from the server? That should work...

**Review by awctw — APPROVED** [review]
lgtm

**Pull request merged**
