### PR TITLE
Add basic habits ui

### PR DESCRIPTION
**Pull request by AlanZhangDev**
Adds basic ui for habits.
Screen Shot 2023-06-08 at 3 34 23 PM

### CODE REVIEW

**Review by awctw — COMMENTED** [review]
Possible to move the module to the second row so there is no overlapping?

**Comment by AlanZhangDev** [comment]
There is a horizontal scroll already, so nothing is blocked.

If we are to move the module to the second row, a better approach would just to make the container flex-wrap.

**Comment by awctw** [comment]
Yeah I think not having to rely on horizontal scroll would probably look better?

**Comment by AlanZhangDev** [comment]
I've added the flex wrap property, so it should be fine on normal monitors.

However there are innate structural problems due to the sidebar being fixed, which could perhaps be settled later.

**Review by awctw — APPROVED** [review]
lgtm

**Pull request merged**
