### PR TITLE
Milestone 3 Express Backend integration with TODOList module frontend.

### PR DESCRIPTION
**Pull request by HeinzUBC**
I have implemented the REST API route handlers for TODOList.

I have finished implementing the thunk and service files for TODOList module. The todoListReducer has also been updated to handle calls to thunks.

I have updated the frontend components of TODOList to dispatch the correct thunk calls. Therefore, frontend has been connected to the Express node backend.

I have also updated the sidebar component so that TODOList table shows the correct number of TODOItems stored in the backend so far.

I have also created a TODOList.config.js file. This is in anticipation to the next step of adding MongoDB database to my module.

### CODE REVIEW

**Comment by kush458** [comment]
Could you delete TODOList.config.js? Since that won't be used later.

**Comment by leungkenneth** [comment]
Deleting a category from the dedicated TODO list page causes no TODOs to be shown until a category is selected again.

Before deleting Biology category:
image

After deleting Biology category:
image

**Comment by leungkenneth** [comment]
When adding a TODO, after typing in a category manually or selecting a pre-existing one, clicking the category dropdown arrow shows nothing (when typing something in) or only the category that was selected in the dropdown list. Could be slightly frustrating for someone who changed their mind on their category to have to delete what is in the textbox in order to access all the categories from the dropdown list again. Though its unknown whether or not users will be okay with this given the category searching that happens when you type something out.

**Comment by leungkenneth** [comment]
When selecting a category to search for the category doesn't show up in the category box to show what is currently being filtered.

**Comment by leungkenneth** [comment]
image


This is an example object I used when setting up the Gantt Chart. In order for the Gantt Chart to use TODO data it will need to at least have a start time and end time/duration. However, other things in the object could serve as future enhancements such as repeating TODOs. Color is something that could potentially be handled from the chart side.

**Comment by HeinzUBC** [comment]
Do not approve this pull request until after the milestone 3 demo

**Review by leungkenneth — APPROVED** [review]

**Pull request merged**
