### PR TITLE
Report and cleanup

### PR DESCRIPTION
**Pull request by leungkenneth**
- Added final report and updated setup instructions in README
- Added back in user.isLoggedIn check for Gantt Chart intiialization
- Removed unused imports, constants, etc.
- Removed unnecessary files, comments, and commented out code
- Added in eslint ignores for exhaustive deps

### CODE REVIEW

**Review by HeinzUBC — CHANGES_REQUESTED** [review]
Not good. I have already made the necessary changes to TODOList components in main. Many of these changes are redundant. Also, you removed the un-selected function of CalendarView. Please create a new branch from main, make the Gantt chart fixes there, and then create a new pull request

**Comment by HeinzUBC** [comment]
Ok. It seems to work well. But in the future, please don't clean up other modules without checking its state in main branch first

**Review by HeinzUBC — APPROVED** [review]

**Comment by leungkenneth** [comment]
> Ok. It seems to work well. But in the future, please don't clean up other modules without checking its state in main branch first

The merge happened during the cleanup so unless I am compulsively checking main I would not be able to catch it.

**Comment by HeinzUBC** [comment]
I guess then pull from main periodically then haha

**Pull request merged**
